# Generated by Django 4.2.2 on 2023-06-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='Введите текст новости', verbose_name='Текст новости'),
        ),
    ]
