# Generated by Django 4.2.2 on 2023-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Заголовок новости'),
        ),
    ]
